---
eck-kibana:
  # Count of Kibana replicas to create.
  #
  count: 1

  # Reference to ECK-managed Elasticsearch resource, ideally from {{ "elasticsearch.fullname" }}
  # Should be used only when deploying the individual eck-kibana chart or eck-stack without Elasticsearch
  # Comment it out if you are deploying eck-kibana as part of the eck-stack chart with Elasticsearch
  # elasticsearchRef:
  #   name: es-quickstart-eck-elasticsearch
  #   namespace: default
  http:
    service:
      spec:
        # Type of service to deploy for Kibana.
        # This deploys a load balancer in a cloud service provider, where supported.
        # 
        type: LoadBalancer
    # tls:
    #   selfSignedCertificate:
    #     subjectAltNames:
    #     - ip: 1.2.3.4
    #     - dns: kibana.example.com
