apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.6.1
  nodeSets:
    - name: default
      count: 3
      config:
        node.store.allow_mmap: false
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  count: 3
  version: 8.6.1
  config:
    log.level: info
    api.http.host: "0.0.0.0"
    queue.type: memory
  services:
    - name: metrics
      service:
        spec:
          type: ClusterIP
          ports:
            - port: 9600
              name: "stats"
              protocol: TCP
              targetPort: 9600
    - name: beats
      service:
        spec:
          type: ClusterIP
          ports:
            - port: 5044
              name: "beats"
              protocol: TCP
              targetPort: 5044
