apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: enterpriselicenses.elasticsearch.k8s.elastic.co
spec:
  group: elasticsearch.k8s.elastic.co
  names:
    kind: EnterpriseLicense
    plural: enterpriselicenses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterLicenses:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      expiryDateInMillis:
                        format: int64
                        type: integer
                      issueDateInMillis:
                        format: int64
                        type: integer
                      issuedTo:
                        type: string
                      issuer:
                        type: string
                      maxNodes:
                        format: int64
                        type: integer
                      signatureRef:
                        type: object
                      startDateInMillis:
                        format: int64
                        type: integer
                      type:
                        type: string
                      uid:
                        type: string
                    required:
                    - uid
                    - type
                    - issueDateInMillis
                    - expiryDateInMillis
                    - maxNodes
                    - issuedTo
                    - issuer
                    - startDateInMillis
                    - signatureRef
                    type: object
                  status:
                    properties:
                      licenseStatus:
                        type: string
                    required:
                    - licenseStatus
                    type: object
                type: object
              type: array
            expiryDateInMillis:
              format: int64
              type: integer
            issueDateInMillis:
              format: int64
              type: integer
            issuedTo:
              type: string
            issuer:
              type: string
            maxNodes:
              format: int64
              type: integer
            signatureRef:
              type: object
            startDateInMillis:
              format: int64
              type: integer
            type:
              type: string
            uid:
              type: string
          required:
          - uid
          - type
          - issueDateInMillis
          - expiryDateInMillis
          - maxNodes
          - issuedTo
          - issuer
          - startDateInMillis
          - signatureRef
          type: object
        status:
          properties:
            licenseStatus:
              type: string
          required:
          - licenseStatus
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
