# The following example should only be used in conjunction with the 'eck-fleet-server' Helm Chart,
# and shows how the Agents can be deployed as a daemonset, and controlled by Fleet Server.
#
version: 9.1.0

# This must match the name of an Agent policy.
policyID: eck-agent
# This must match the name of the fleet server installed from eck-fleet-server chart.
fleetServerRef:
  name: eck-fleet-server
kibanaRef:
  name: eck-kibana
mode: fleet
# elasticsearchRefs must be empty when fleet mode is enabled.
elasticsearchRefs: []
daemonSet:
  podTemplate:
    spec:
      serviceAccountName: elastic-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 0
