---
apiVersion: autoops.k8s.elastic.co/v1alpha1
kind: AutoOpsAgentPolicy
metadata:
  name: {{ include "autoops.fullname" . }}
  labels:
    {{- include "autoops.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "An AutoOps Agent Policy version is required" .Values.version }}
  {{- with .Values.image }}
  image: {{ . }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.podTemplate }}
  podTemplate:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  config:
    {{- if .Values.configRef }}
    secretName: {{ required "configRef.secretName is required when configRef is specified" .Values.configRef.secretName }}
    {{- else }}
    secretName: {{ printf "%s-config" (include "autoops.fullname" .) }}
    {{- end }}
  {{- with .Values.resourceSelector }}
  resourceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}

