apiVersion: v2
name: eck-package-registry
description: Elastic Package Registry managed by the ECK operator
kubeVersion: ">= 1.21.0-0"
type: application
version: 0.19.0-SNAPSHOT
sources:
  - https://github.com/elastic/cloud-on-k8s
  - https://github.com/elastic/package-registry
