bases:
  - ../crds

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1beta1
      kind: CustomResourceDefinition
      name: apmservers.apm.k8s.elastic.co
    path: apm-and-kibana-podtemplate-patch.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1beta1
      kind: CustomResourceDefinition
      name: elasticsearches.elasticsearch.k8s.elastic.co
    path: elasticsearch-podtemplate-patch.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1beta1
      kind: CustomResourceDefinition
      name: kibanas.kibana.k8s.elastic.co
    path: apm-and-kibana-podtemplate-patch.yaml