---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eck-{{ .Context.TestRun }}"
  namespace: {{ .Context.E2ENamespace }}
  labels:
    test-run: {{ .Context.TestRun }}
data:
  testcontext.json: |
{{ .Context | toPrettyJson | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "eck-{{ .Context.TestRun }}"
  namespace: {{ .Context.E2ENamespace }}
  labels:
    test-run: {{ .Context.TestRun }}
spec:
  ttlSecondsAfterFinished: 360
  template:
    metadata:
      annotations:
        co.elastic.logs/json.keys_under_root: "true"
{{- if and .Context.AutopilotCluster (semverCompare ">= 1.27.0-0" .Context.KubernetesVersion.String) }}
        # as of version 1.27 Autopilot clusters support this annotation used here to avoid evictions of the test runner
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
{{ end }}
      labels:
        test-run: {{ .Context.TestRun }}
        stream-logs: "true"
    spec:
      securityContext:
        runAsNonRoot: true
{{ if not .Context.OcpCluster }}
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 0
{{ end }}
      serviceAccountName: {{ .Context.E2EServiceAccount }}
      containers:
        - name: e2e
          image: {{ .Context.E2EImage }}
          imagePullPolicy: IfNotPresent
          args: [{{- with .Context.TestRegex -}}"-run", "{{ . }}",{{- end -}}"-args", "-testContextPath","/etc/e2e/testcontext.json"]
          volumeMounts:
            - name: test-config
              mountPath: /etc/e2e
            - name: test-secrets
              mountPath: /var/run/secrets/e2e
{{ if .Context.AutopilotCluster }}
            - name: tmp
              mountPath: /tmp
          # If resources aren't assigned in autopilot
          # it will assign a tiny amount of cpu
          # which causes e2e tests to be very slow.
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
{{ end }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: E2E_JSON
              value: "{{ .Context.LogToFile }}"
            - name: E2E_TAGS
              value: "{{ .Context.E2ETags }}"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ARTEFACTS_DIR
              value: "{{ .Context.ArtefactsDir }}"
            - name: CLUSTER_NAME
              value: "{{ .Context.ClusterName }}"
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/done
      volumes:
        - name: test-config
          configMap:
            name: "eck-{{ .Context.TestRun }}"
        - name: test-secrets
          secret:
            secretName: "eck-{{ .Context.TestRun }}"
{{ if .Context.AutopilotCluster }}
        - name: tmp
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "e2e-default"
                resources:
                  requests:
                    storage: 10Gi
{{ end }}
      restartPolicy: Never
  backoffLimit: 0 # don't retry a failed test
