---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eck-{{ .Context.TestRun }}"
  namespace: {{ .Context.E2ENamespace }}
  labels:
    test-run: {{ .Context.TestRun }}
data:
  testcontext.json: |
{{ .Context | toPrettyJson | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "eck-{{ .Context.TestRun }}"
  namespace: {{ .Context.E2ENamespace }}
  labels:
    test-run: {{ .Context.TestRun }}
spec:
{{ if not .Context.Ocp3Cluster }}
  ttlSecondsAfterFinished: 360
{{ end }}
  template:
    metadata:
      annotations:
        co.elastic.logs/json.keys_under_root: "true"
      labels:
        test-run: {{ .Context.TestRun }}
        stream-logs: "true"
    spec:
      securityContext:
        runAsNonRoot: true
{{ if not .Context.OcpCluster }}
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 0
{{ end }}
      serviceAccountName: {{ .Context.E2EServiceAccount }}
      containers:
        - name: e2e
          image: {{ .Context.E2EImage }}
          imagePullPolicy: IfNotPresent
          args: [{{- if .Context.TestRegex -}}"-run", "{{ .Context.TestRegex }}",{{- end -}}"-args", "-testContextPath","/etc/e2e/testcontext.json"]
          volumeMounts:
            - name: test-config
              mountPath: /etc/e2e
            - name: test-secrets
              mountPath: /var/run/secrets/e2e
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
        - name: test-config
          configMap:
            name: "eck-{{ .Context.TestRun }}"
        - name: test-secrets
          secret:
            secretName: "eck-{{ .Context.TestRun }}"
      restartPolicy: Never
  backoffLimit: 0 # don't retry a failed test
