---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ekmnt
  namespace: istio-apps
  labels:
    app: ekmnt
spec:
  version: 8.1.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: 1
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          app: ekmnt
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  - name: data
    count: 1
    config:
      node.roles: ["data"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          app: ekmnt
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  - name: ingest
    count: 1
    config:
      node.roles: ["ingest"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          app: ekmnt
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  - name: coordinating
    count: 1
    config:
      node.roles: []
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          app: ekmnt
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  - name: ml
    count: 1
    config:
      node.roles: ["ml"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          app: ekmnt
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ekmnt
  namespace: istio-apps
  labels:
    app: ekmnt
spec:
  version: 8.1.1
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: ekmnt
  podTemplate:
    metadata:
      labels:
        app: ekmnt
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
