# This sample sets up a single Kibana instance pointing to a remote Elasticsearch cluster
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.3.0
  elasticsearch:
    url: https://url.to.elasticsearch:9200
    auth:
      # reference to a secret containing credentials in the given key
      secret:
        name: secret-name
        key: user # key is the user, value is the password for that user
    certificateAuthorities:
      secretName: my-ca-cert # reference to a secret containing certificates under "tls.crt"
  nodeCount: 1
#   http:
#     service:
#       spec:
#         type: LoadBalancer # default is clusterIP
#   # inject secure settings into Kibana keystore from k8s secrets references
#   secureSettings:
#   - secretName: ref-to-secret
#   - secretName: another-ref-to-secret
#     # expose only a subset of the secret keys (optional)
#     items:
#     - key: value1
#       path: newkey # project a key to a specific path (optional)
