apiVersion: deployments.k8s.elastic.co/v1alpha1
kind: Stack
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: stack-sample
spec:
  # Add fields here
  version: "6.4.2"
  elasticsearch:
    nodeCount: 3
