apiVersion: v2
name: eck-elasticsearch
description: A Helm chart to deploy Elasticsearch managed by the ECK Operator.
kubeVersion: ">= 1.21.0-0"
type: application
version: 0.1.1
sources:
  - https://github.com/elastic/cloud-on-k8s
  - https://github.com/elastic/elasticsearch/
icon: https://helm.elastic.co/icons/elasticsearch.png
