---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.12.0
  count: 1
  config:
    # Configure this to a domain you control
    map.emsUrl: https://maps.{{YOUR_DOMAIN}}
  elasticsearchRef:
    name: elasticsearch
