# Very similar to a global operator, but with
# a different service account and different run arguments
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: <NAMESPACE>
  labels:
    control-plane: elastic-operator
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      annotations:
        "co.elastic.logs/raw": "[{\"type\":\"container\", \"json.keys_under_root\": true, \"paths\": [\"/var/log/containers/*${data.kubernetes.container.id}.log\"], \"processors\":[{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"error\",\"to\":\"_error\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_error\",\"to\":\"error.message\"}]}}]}]"
        #"co.elastic.logs/json.keys_under_root": "true"
        #"co.elastic.logs/json.add_error_key": "true"
        #"co.elastic.logs/json.message_key": "message"
        #"co.elastic.logs/processors.rename.fields.from": "error"
        #"co.elastic.logs/processors.rename.fields.to": "error.message"
      labels:
        control-plane: elastic-operator
    spec:
      serviceAccountName: elastic-operator
      containers:
      - image: <OPERATOR_IMAGE>
        name: manager
        args: ["manager", "--operator-roles", "all", "--log-verbosity=0"]
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_SECRET
            value: elastic-webhook-server-cert
          - name: WEBHOOK_PODS_LABEL
            value: elastic-operator
          - name: OPERATOR_IMAGE
            value: <OPERATOR_IMAGE>
        resources:
          limits:
            cpu: 1
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: elastic-webhook-server-cert
