apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <OPERATOR_NAME>
  namespace: <NAMESPACE>
  labels:
    control-plane: <OPERATOR_NAME>
spec:
  selector:
    matchLabels:
      control-plane: <OPERATOR_NAME>
  serviceName: <OPERATOR_NAME>
  template:
    metadata:
      annotations:
        # Rename the fields "error" to "error.message" and "source" to "event.source"
        # This is to avoid a conflict with the ECS "error" and "source" documents.
        "co.elastic.logs/raw": "[{\"type\":\"container\",\"json.keys_under_root\":true,\"paths\":[\"/var/log/containers/*${data.kubernetes.container.id}.log\"],\"processors\":[{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"error\",\"to\":\"_error\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_error\",\"to\":\"error.message\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"source\",\"to\":\"_source\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_source\",\"to\":\"event.source\"}]}}]}]"
      labels:
        control-plane: <OPERATOR_NAME>
    spec:
      serviceAccountName: <OPERATOR_NAME>
      containers:
      - image: <OPERATOR_IMAGE>
        name: manager
        # namespaces the k8s client can access objects in should include the managed namespaces and the namespace the operator resides in, to be able to fetch internal secrets
        args: ["manager", "--namespaces", "<MANAGED_NAMESPACE_LIST>,<NAMESPACE>"]
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_IMAGE
            value: <OPERATOR_IMAGE>
        resources:
          limits:
            cpu: 1
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
