apiVersion: v2
  
name: eck-operator-crds

icon: https://helm.elastic.co/icons/eck.png

description: ECK operator Custom Resource Definitions

type: application

version: 2.15.0-SNAPSHOT

appVersion: 2.15.0-SNAPSHOT

home: https://github.com/elastic/cloud-on-k8s

kubeVersion: ">=1.21.0-0"

keywords:
  - Logstash
  - Elasticsearch
  - Kibana
  - APM Server
  - Beats
  - Enterprise Search
  - Elastic Stack
  - Operator

maintainers:
  - name: Elastic
    email: eck@elastic.co
