apiVersion: v2
  
name: eck-operator-crds

icon: https://helm.elastic.co/icons/eck.png

description: |-
  A Helm chart for installing the ECK operator Custom Resource Definitions (CRD). 

type: application

version: 2.3.0

appVersion: 2.3.0

home: https://github.com/elastic/cloud-on-k8s

kubeVersion: ">=1.12.0-0"

keywords:
  - Elasticsearch
  - Kibana
  - APM Server
  - Beats
  - Enterprise Search
  - Elastic Stack
  - Operator

maintainers:
  - name: Elastic
    email: eck@elastic.co
