processor:
  ignoreTypes:
    - "(Elasticsearch|ElasticsearchAutoscaler|Kibana|ApmServer|EnterpriseSearch|Beat|Agent|StackConfigPolicy|Logstash)List$"
    - "(Kibana|ApmServer|EnterpriseSearch|Beat|Agent|StackConfigPolicy)Health$"
    - "(ElasticsearchAutoscaler|Kibana|ApmServer|Reconciler|EnterpriseSearch|Beat|Agent|Maps|Policy)Status$"
    - "ElasticsearchSettings$"
    - "Associa(ted|tion|tionStatus|tionConf)$"
    - "AssociationStatusMap"
    - "APM(Es|Kibana)Association"
    - "NodeSet(List|ConfigError)$"
    - "Autoscaling*"
    - "(NodeSets|NodeSet|Cluster)Resources"
    - NamespacedSecretSource
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: "1.20"
