---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eck-{{ .TestRun }}"
  namespace: {{ .E2ENamespace }}
  labels:
    test-run: {{ .TestRun }}
data:
  testcontext.json: |
{{ . | toPrettyJson | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "eck-{{ .TestRun }}"
  namespace: {{ .E2ENamespace }}
  labels:
    test-run: {{ .TestRun }}
spec:
  ttlSecondsAfterFinished: 360
  template:
    metadata:
      labels:
        test-run: {{ .TestRun }}
    spec:
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      serviceAccountName: {{ .E2EServiceAccount }}
      containers:
        - name: e2e
          image: {{ .E2EImage }}
          imagePullPolicy: Always
          args: ["-run", "{{ .TestRegex }}", "-args", "-testContextPath","/etc/e2e/testcontext.json"]
          volumeMounts:
            - name: test-config
              mountPath: /etc/e2e
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: test-config
          configMap:
            name: "eck-{{ .TestRun }}"
      restartPolicy: Never
  backoffLimit: 0 # don't retry a failed test
