apiVersion: v2
name: eck-kibana
description: Kibana managed by the ECK operator
kubeVersion: ">= 1.21.0-0"
type: application
version: 0.6.0
sources:
  - https://github.com/elastic/cloud-on-k8s
  - https://github.com/elastic/kibana
icon: https://helm.elastic.co/icons/kibana.png
