# This sample sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: "7.1.0"
  nodes:
  - config:
      # most Elasticsearch configuration parameters are possible to set, e.g:
      node.attr.attr_name: attr_value
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: true
    podTemplate:
      metadata:
        labels:
          # additional labels for pods
          foo: bar
      spec:
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    nodeCount: 3
#    # request 2Gi of persistent data storage for pods in this topology element
#    volumeClaimTemplates:
#    - metadata:
#        name: elasticsearch-data
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 2Gi
#        storageClassName: standard
#  # inject secure settings into Elasticsearch nodes from a k8s secret reference
#   secureSettings:
#     secretName: "ref-to-secret"
#   http:
#     service:
#       spec:
#         # expose this cluster Service with a LoadBalancer
#         type: LoadBalancer
#     tls:
#       # add a list of SANs into the self-signed HTTP certificate
#       selfSignedCertificate:
#         subjectAltNames:
#         - ip: 192.168.1.2
#         - ip: 192.168.1.3
#         - dns: elasticsearch-sample.example.com
