apiVersion: v2
name: eck-apm-server
description: Elastic APM Server managed by the ECK operator
kubeVersion: ">= 1.21.0-0"
type: application
version: 0.13.0-SNAPSHOT
sources:
  - https://github.com/elastic/cloud-on-k8s
  - https://github.com/elastic/apm-server
icon: https://helm.elastic.co/icons/apm.png
