apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: trust-one
  labels:
    k8s.elastic.co/expected-license: "trial"
spec:
  licenseType: trial # can be "basic", "trial", "gold", "platinum"
  version: "6.6.2"
  setVmMaxMapCount: true
  topology:
    - nodeTypes:
        master: true
        data: true
        ingest: true
      resources:
        limits:
          memory: 1Gi
          cpu: 1
      nodeCount: 1
  expose: ClusterIP
---
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: trust-two
  labels:
    k8s.elastic.co/expected-license: "trial"
spec:
  version: "6.6.2"
  licenseType: trial # can be "basic", "trial", "gold", "platinum"
  setVmMaxMapCount: true
  topology:
    - nodeTypes:
        master: true
        data: true
        ingest: true
      resources:
        limits:
          memory: 1Gi
          cpu: 1
      nodeCount: 1
  expose: ClusterIP
