{{- if $.Values.agent.enabled -}}
{{- include "elasticagent.preset.init" $ -}}
{{- range $presetName, $presetVal := $.Values.agent.presets }}
{{- $agentName := printf "agent-%s" (lower $presetName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $agentName }}
  namespace: {{ .namespace | default $.Release.Namespace | quote }}
  labels:
    {{- include "elasticagent.labels" $ | nindent 4 }}
    {{- with ($presetVal).labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($presetVal).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  agent.yml: |-
    id: {{ $agentName }}
    secret_references: []
    {{- with ($presetVal).agent }}
    agent:
      {{- . | toYaml | nindent 6}}
    {{- end }}
    {{- with ($presetVal).providers }}
    providers:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    inputs:
    {{- with ($presetVal)._inputs -}}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
---
{{ end -}}
{{- end }}