apiVersion: v2

name: eck

description: |-
  A Helm chart for deploying Elastic Cloud on Kubernetes (ECK): the official Kubernetes operator for orchestrating Elasticsearch, Kibana, APM Server, Enterprise Search, and Beats.

home: https://github.com/elastic/cloud-on-k8s

type: application

version: 1.0.0-beta1

appVersion: 1.3.0-SNAPSHOT

kubeVersion: ">= 1.12"

keywords:
  - Elasticsearch
  - Kibana
  - APM Server
  - Beats
  - Enterprise Search
  - Elastic Stack
  - Operator

maintainers:
  - name: Elastic
    email: eck@elastic.co
