---
apiVersion: autoops.k8s.elastic.co/v1alpha1
kind: AutoOpsAgentPolicy
metadata:
  name: {{ include "autoops.fullname" . }}
  labels:
    {{- include "autoops.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: enterprise
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "An AutoOps Agent Policy version is required" .Values.version }}
  {{- with .Values.image }}
  image: {{ . }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.podTemplate }}
  podTemplate:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  autoOpsRef:
    secretName: {{ required "autoOpsRef.secretName is required to reference the AutoOps configuration secret" .Values.autoOpsRef.secretName }}
  resourceSelector:
    {{- required "resourceSelector is required" .Values.resourceSelector | toYaml | nindent 4 }}

