---
apiVersion: packageregistry.k8s.elastic.co/v1alpha1
kind: PackageRegistry
metadata:
  name: {{ include "epr.fullname" . }}
  labels:
    {{- include "epr.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "A Elastic Package Registry version is required" .Values.version }}
  {{- with (.Values.image) }}
  image: {{ . }}
  {{- end }}
  {{- with (.Values.count) }}
  count: {{ . }}
  {{- end }}
  {{- with (.Values.config) }}
  config:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with (.Values.http) }}
  http:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (.Values.podTemplate) }}
  podTemplate:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with (.Values.revisionHistoryLimit) }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
